[package]
name = "simple-web-server"
version = "0.1.0"
edition = "2021"
authors = ["Andrey Khalepov"]
description = "Simple web server with thread pool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
